services:
  - type: web
    name: wanna-learn-more-about-you
    env: python
    buildCommand: "./build.sh"
    startCommand: "python manage.py runserver 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6